CONTAINER_TOP_BG_COLOR = '#6e9b43'
CONTAINER_TOP_FG_COLOR = 'White'
CONTAINER_LEFT_BG_COLOR = '#d4e8c5'
CONTAINER_LEFT_FG_COLOR = 'Black'
CONTAINER_CENTER_BG_COLOR = 'White'
CONTAINER_CENTER_FG_COLOR = 'Black'
CONTAINER_RIGHT_BG_COLOR = '#d4e8c5'
CONTAINER_RIGHT_FG_COLOR = 'Black'
CONTAINER_BOTTOM_BG_COLOR = '#6b6b6b'
CONTAINER_BOTTOM_FG_COLOR = 'White'

TEXT_FONT = ("tahoma", "11", "normal")
NORMAL_FONT = ('Tahoma','16',"normal")
BOLD_FONT = ('Tahoma','16',"bold")

TOOLTIP_BG = 'White'
TOOLTIP_FG = 'Black'
TOOLTIP_FONT = ("tahoma", "8", "normal")